maila_2d_sim:
  ubuntu:
  - ros-iron-maila-2d-sim
maila_bringup:
  ubuntu:
  - ros-iron-maila-bringup
stage:
  ubuntu:
  - ros-iron-stage
stage_ros2:
  ubuntu:
  - ros-iron-stage-ros2
vesc:
  ubuntu:
  - ros-iron-vesc
vesc_msgs:
  ubuntu:
  - ros-iron-vesc-msgs
vesc_ackermann:
  ubuntu:
  - ros-iron-vesc-ackermann
vesc_driver:
  ubuntu:
  - ros-iron-vesc-driver
