maila_2d_sim:
  ubuntu:
  - ros-rolling-maila-2d-sim
stage:
  ubuntu:
  - ros-rolling-stage
stage_ros2:
  ubuntu:
  - ros-rolling-stage-ros2
vesc:
  ubuntu:
  - ros-rolling-vesc
vesc_msgs:
  ubuntu:
  - ros-rolling-vesc-msgs
vesc_ackermann:
  ubuntu:
  - ros-rolling-vesc-ackermann
vesc_driver:
  ubuntu:
  - ros-rolling-vesc-driver
