maila_2d_sim:
  ubuntu:
  - ros-humble-maila-2d-sim
maila_bringup:
  ubuntu:
  - ros-humble-maila-bringup
stage:
  ubuntu:
  - ros-humble-stage
stage_ros2:
  ubuntu:
  - ros-humble-stage-ros2
vesc:
  ubuntu:
  - ros-humble-vesc
vesc_msgs:
  ubuntu:
  - ros-humble-vesc-msgs
vesc_ackermann:
  ubuntu:
  - ros-humble-vesc-ackermann
vesc_driver:
  ubuntu:
  - ros-humble-vesc-driver
