name: build
# Template taken from: https://github.com/moveit/moveit2_packages/blob/main/.github/workflows/build.yaml

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * *'

# Cancel in-progress funs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_job:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        ros_distro: [humble, rolling]
    name: build_${{ matrix.ros_distro }}
    runs-on: ubuntu-22.04
    env:
      branch: ${{ github.ref_name }}
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: ${{ matrix.ros_distro }}
          REPOS_FILE: https://raw.githubusercontent.com/Mailamaca/maila_packages/${{ env.branch }}/sources.repos
          ROSDEP_SOURCE: "yaml https://raw.githubusercontent.com/Mailamaca/maila_packages/${{ env.branch }}/maila-rosdep.yaml"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
